export const FETCH_USER = "FETCH_USER";
// ---
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
// ---
export const FETCH_SHOPS = "FETCH_SHOPS";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_USER_SHOPS = "FETCH_USER_SHOPS";
// ---
export const FETCH_DEALS = "FETCH_DEALS";
export const FETCH_DEAL = "FETCH_DEAL";
export const CREATE_DEAL = "CREATE_DEAL";
// ---
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
// ---
export const FETCH_CUSTOMER = "FETCH_CUSTOMER";
export const FETCH_CUSTOMERS_PENDING = "FETCH_CUSTOMERS_PENDING";
export const FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";
export const FETCH_CUSTOMERS_FAILED = "FETCH_CUSTOMERS_FAILED";

export const CREATE_CUSTOMER_PENDING = "CREATE_CUSTOMER_PENDING";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_FAILED = "CREATE_CUSTOMER_FAILED";
// ---
export const SEARCH_CUSTOMER = "SEARCH_CUSTOMER";
